### ISSUE TITLE
"kamcli acc cdrs-generate"   fails with 'connection' object has no attribute 'commit' (formerly #16/#17)

### ISSUE THREAD

**Issue by Pcrossley69** [kamailio/kamcli#18]
In the packet trace I can now see:
call kamailio_cdrs()
rollback

On the command line I get this:

root@kamcli-2:~#      kamcli acc cdrs-generate
Traceback (most recent call last):
  File "/usr/local/bin/kamcli", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/kamcli/commands/cmd_acc.py", line 245, in acc_cdrs_generate
    c.commit()
AttributeError: 'Connection' object has no attribute 'commit'

**Comment by Pcrossley69** [comment]
I think this is the fix,
In /usr/local/lib/python3.8/dist-packages/kamcli/commands/cmd_acc.py
-----------------------------------------------------------------------
Line 239
-------------------------------------------------------------
def acc_cdrs_generate(ctx):
    """Run SQL stored procedure to generate CDRS"""
    ctx.vlog("Run SQL stored procedure to generate CDRS")
    e = create_engine(ctx.gconfig.get("db", "rwurl"))
    with e.connect() as c:
        t=c.begin()
        c.execute("call kamailio_cdrs()")
        t.commit()
------------------------------------------------------------------------------------------------------
Line 417
----------------------------------------------------------------------------------------------------
def acc_rates_generate(ctx):
    """Run SQL stored procedure to rate the CDRS and generate the costs"""
    ctx.vlog(
        "Run SQL stored procedure to rate the CDRS and generate the costs"
    )
    e = create_engine(ctx.gconfig.get("db", "rwurl"))
    with e.connect() as c:
        t=c.begin
        c.execute("call kamailio_rating()")
        t.commit()
--------------------------------------------------------------------

It doesn't explain the spurious rollback that follows the commit but it does at least commit before the rollback
