### ISSUE TITLE
TypeError when running kamcli pstrap with our without arguments

### ISSUE THREAD

**Issue by medOualla** [kamailio/kamcli#30]
I am facing an issue when running the `kamcli pstrap` command with or without its arguments **-a** or **-s**. The command results in a **TypeError**. Other commands are working fine.

**Environment:**
- **OS:** Debian 11(bullseye) docker container
- **Python version:** Python 3.9.2
- **kamcli version:**  kamcli, version 3.0.0
- **kamailio version:**  kamailio 5.7.6 (x86_64/linux) f9e811
    flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, MEM_JOIN_FREE, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
    ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
    poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
    id: f9e811
    compiled on 18:01:41 Nov  8 2024 with gcc 10.2.1

**Error Message:**
```
Trap file: /tmp/gdb_kamailio_20241109_124842.txt
Trapping Kamailio processes with gdb. It can take a while.
.Traceback (most recent call last):
  File "/usr/local/bin/kamcli", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/kamcli/commands/cmd_pstrap.py", line 68, in cli
    'echo "---start '
TypeError: can only concatenate str (not "bytes") to str
```

**Comment by miconda** [comment]
Can you try with latest git version? I pushed a commit to try to fix it, but I didn't have the chance to test it.

**Comment by medOualla** [comment]
I have tried the latest git version, the **`kamcli pstrap`** commands works fine now.
Thank you @miconda .
